### ISSUE TITLE
Permissions do nothing

### ISSUE THREAD

**Issue by jango-bob** [CorneliusMa/SilkSpawners_v2#16] opened 2022-09-04 19:51 UTC
Adding permissions with groupmanager has done nothing, nobody can place anything or get a spawner back.

**Comment by CorneliusMa** [comment] 2022-09-16 14:29
Hello, permissions work for me. Can you tell me what permissions you have set?

**Comment by jango-bob** [comment] 2022-09-16 15:14
I have every single one enabled on groupmanagerx and set the rank to
default. They only work then you’re a server op

**Comment by CorneliusMa** [comment] 2022-09-16 15:29
This was a problem caused by GroupManager. Its fixed now

**Closed by CorneliusMa** 2022-09-16 15:29 UTC
