### ISSUE TITLE
spawners turning pig

### ISSUE THREAD

**Issue by pump61** [CorneliusMa/SilkSpawners_v2#15] opened 2022-08-17 16:42 UTC
Spawners are turning pig when placed on the ground

**Comment by RealFinePoint** [comment] 2022-08-20 17:41
I'm also having this issue, specifically for bedrock players after clicking soon after it's placed.

**Comment by CorneliusMa** [comment] 2022-08-21 20:11
I'm currently very busy, but will fix this asap

**Comment by frankinbaka** [comment] 2022-09-16 01:26
Really, and still not fixed, even after almost 1 month :c

**Comment by CorneliusMa** [comment] 2022-09-16 15:31
I can't reproduce your problem. Have you set the correct permissions and are you using spigot/paper?

**Comment by frankinbaka** [comment] 2022-09-16 19:38
Yes yes, simply the spawners of the players that were stored in the chests, when they take it to put it in the chosen place, it simply turns into a pig.

Yes, I use spigot/paper

**Comment by RealFinePoint** [comment] 2022-09-17 10:01
I'm still having this problem, but specifically for Bedrock players (via Geyser) who click too fast after placing it. 
It sounds like a different issue than what OP is complaining about.

**Comment by PedroMPagani** [comment] 2022-10-07 10:11
@CorneliusMa I'm having this issue too, we're running 500 players online (DonutSMP), and at least 300 of those are bedrock users, almost all the reports came from bedrock players.

**Comment by PedroMPagani** [comment] 2022-10-07 10:13
I'll debug your code and implement it in the server, if I get any good info I'll do a PR, sounds good?

**Comment by PedroMPagani** [comment] 2022-10-07 10:15
Yeah, so here's the logs:

07/10/2022 10:10:52 User T0R8EN broke a spawner PIG at 21711 -55 33973
07/10/2022 10:10:54 User T0R8EN placed a spawner PIG at 21711 -55 33973

When the user breaks it, the entity type is PIG for some reason.

**Comment by PedroMPagani** [comment] 2022-10-07 10:35
You know, my best guess is that they're kind of breaking it before the setSpawnerType method runs, which makes it so its a PIG

**Comment by PedroMPagani** [comment] 2022-10-07 10:36
Maybe a safety implementation usage of the PersistentDataContainers would be good, so you'd basically set them when the spawner is getting placed, and remove them when the setSpawnerType finishes its job

**Comment by PedroMPagani** [comment] 2022-10-07 10:51
Hey, so I figured what the issue is.
```java
[10:50:51 INFO]: Entity type: CREEPER itemStack: ItemStack{AIR x 0, UNSPECIFIC_META:{meta-type=UNSPECIFIC, display-name={"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"light_purple","text":"Spawner"}],"text":""}, lore=[{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"yellow","text":"Creeper"}],"text":""}]}}
[10:50:51 INFO]: [SPAWNER CHANGE]
[10:50:51 INFO]: Entity type: PIG itemStack: ItemStack{SPAWNER x 1, TILE_ENTITY_META:{meta-type=TILE_ENTITY, display-name={"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"light_purple","text":"Spawner"}],"text":""}, lore=[{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"yellow","text":"Pig"}],"text":""}], blockMaterial=SPAWNER}}
```

**Comment by PedroMPagani** [comment] 2022-10-07 10:51
Basically if the player clicks too fast, the PlayerInteractEvent in the SpawnerChange cancells and sets the spawner to pig, I'll make a PR for it.

**Comment by PedroMPagani** [comment] 2022-10-07 10:52
It kind of needs to run in almost the same tick

**Comment by PedroMPagani** [comment] 2022-10-07 17:53
The pr was sent some time ago, if you could merge it @CorneliusMa

**Comment by CorneliusMa** [comment] 2022-10-08 18:39
Hi @PedroMPagani 
Thanks a lot for your help, I will take a look at the pr

**Comment by RealFinePoint** [comment] 2022-10-15 00:27
Was this merged?

**Comment by CorneliusMa** [comment] 2022-10-16 10:56
Just merged it

**Closed by CorneliusMa** 2022-10-16 10:56 UTC
Labels: bug
